# fly.toml app configuration file generated for dash-floral-tree-9601 on 2025-02-03T00:35:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dash-floral-tree-9601'
primary_region = 'lhr'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'dash.yellowsign.uk'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
