name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          elixir-version: 1.17.3

      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: mix test --warnings-as-errors
      - run: mix sobelow -i Config.HTTPS,Config.CSP # TODO: fix CSP
      - run: mix credo --strict
