name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2.2
          elixir-version: 1.18.2
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix lint
      - run: mix test --warnings-as-errors
